### ISSUE TITLE
验证码总是输入不对

### ISSUE THREAD

**Issue by freeasbird** [wenjianzhang/go-admin#10]
验证码总是输入不对, 不知道是不是程序的bug,还是我一直看错  :)))) .  请换个环境测试下.
另外建议增加sqlite3的支持, 毕竟测试平台搭建更简单

**Comment by wenjianzhang** [comment]
验证码看不清楚是可以点击图片替换的。

**Comment by freeasbird** [comment]
嗯,我点过很多次了.  我用其他系统没有这个问题,蛮神奇的. 就当我没说

**Comment by wenjianzhang** [comment]
是线上预览环境吗？

**Comment by freeasbird** [comment]
是的. 有时候非得换一个机器就好了

**Comment by wenjianzhang** [comment]
之前验证码对比度不够明显确实很容易识别错误，但是现在调整了背景颜色相对来说应该是没什么，或许对内容做一下调整吧，有可能是里边存在易混淆的字符，0或者o 等之类，谢谢

**Comment by freeasbird** [comment]
应该不是字符混淆的问题.  工程不错,加油

**Comment by wenjianzhang** [comment]
已经修复，使用数字验证码了，你可以尝试一下，这个验证码和机器是没有关系的，源码过段时间才能够提交哦
