### ISSUE TITLE
go build 失败

### ISSUE THREAD

**Issue by chengang2** [wenjianzhang/go-admin#101]
go: golang.org/x/crypto@v0.0.0-20200323165209-0ec3e9974c59: Get https://proxy.go
lang.org/golang.org/x/crypto/@v/v0.0.0-20200323165209-0ec3e9974c59.mod: dial tcp
 172.217.160.113:443: connectex: A connection attempt failed because the connect
ed party did not properly respond after a period of time, or established connect
ion failed because connected host has failed to respond.

**Comment by keven82** [comment]
set GO111MODULE=on
set GOPROXY=https://goproxy.io
试试

**Comment by wenjianzhang** [comment]
建议使用 goproxy
