### ISSUE TITLE
分页没有显示pageSize

### ISSUE THREAD

**Issue by plsof** [wenjianzhang/go-admin#11]
RT
	mp["pageIndex"] = pageSize

->    mp["pageSize"] = pageSize

**Comment by wenjianzhang** [comment]
请描述清楚具体时间那个功能的分页没有显示pagesize？

**Comment by plsof** [comment]
我看了几处分页都这样

	mp["pageIndex"] = pageIndex
	mp["pageIndex"] = pageSize

**Comment by wenjianzhang** [comment]
已修复
