### ISSUE TITLE
关于权限的问题

### ISSUE THREAD

**Issue by qweawdqq** [wenjianzhang/go-admin#111]
设置完页面权限后，进到页面一直提示：对不起，您没有该接口访问权限，请联系管理员
不知道哪里没有设置好。可否对权限这里出一些设计和设置文档

**Comment by wenjianzhang** [comment]
针对权限部门本周会出一个讲解视频；配置完菜单后还需要将对应的5个接口添加进菜单里边；同时给角色添加接口权限，就好了。

**Comment by wenjianzhang** [comment]
https://space.bilibili.com/565616721/channel/detail?cid=125737 b站视频已经更新
