### ISSUE TITLE
文档中的var res models.Response 已经失效

### ISSUE THREAD

**Issue by chanvi** [wenjianzhang/go-admin#118]
package apis

import (
	"github.com/gin-gonic/gin"
	"go-admin/models"
	"net/http"
)

func GetArticleList(c *gin.Context) {
	
	var res models.Response
	res.Data = "hello world ！"

	c.JSON(http.StatusOK, res.ReturnOK())
}

已经改为 var res app.Response 了，但文档没变。

**Comment by wenjianzhang** [comment]
感谢您的提出的问题，将会在最短时间内进行修复，谢谢您对go-admin的关注和支持！
