### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by xiaodingding** [wenjianzhang/go-admin#121]
sqlite如何配置使用，能给一个简单的配置说明吗？

**Comment by wenjianzhang** [comment]
您好，sqlite是一位好心网友贡献的pr，现在已经和正式版本有一些出入了，不过后续将会考虑支持这些数据库类型；谢谢您的支持和关注！

**Comment by wenjianzhang** [comment]
楼上的各位pgsql已经支持，欢迎体验！ dev 分支
