### ISSUE TITLE
关于部署的问题

### ISSUE THREAD

**Issue by qweawdqq** [wenjianzhang/go-admin#135]
vue部分使用打包命令，将生产好的文件夹 放到nginx 里面，在浏览器中请求，可以正常登陆。
后台部分打包放到了linux服务器上了。
奇怪的是进到系统中，感觉后面服务请求的根本不是我自己的后台程序。数据库我都已经改完了，自己还做的页面，但是进到系统里面的显示的数据都是初始化的，根本不是我自己的。
感觉请求的是演示的那个后台，不是我自己写的。
我的问题：
1、不知道是哪个环节出错了，导致这种结果
2、现在我请求的后台是哪里来的？
还请指点

**Comment by wenjianzhang** [comment]
.env.production 这个配置文件中，url修改一下就好了哦！

**Comment by wenjianzhang** [comment]
请问问题解决了吗？

**Comment by qweawdqq** [comment]
已经解决了 ^ ^

**Comment by i11us0ry** [comment]
> 已经解决了 ^ ^

请问具体咋解决的
