### ISSUE TITLE
权限范围设置完毕后，create_by字段填充问题

### ISSUE THREAD

**Issue by zhuqiyun** [wenjianzhang/go-admin#136]
权限范围设置之后，并没有看到前端有地方去填充这个字段，还是一直为空？

**Comment by wenjianzhang** [comment]
请在api处使用 `data.CreateBy = tools.GetUserIdStr(c)`  获取用户标识；需要注意一点，如果使用此函数，对应的接口需要配合使用 jwt 中间件；

**Comment by zhuqiyun** [comment]
> 请在api处使用 `data.CreateBy = tools.GetUserIdStr(c)` 获取用户标识；需要注意一点，如果使用此函数，对应的接口需要配合使用 jwt 中间件；

明白了
