### ISSUE TITLE
用户中心密码修改功能无效

### ISSUE THREAD

**Issue by gitzwt** [wenjianzhang/go-admin#137]
旧密码随便填写,保存都提示修改成功,但无法使用新密码登录 看了表里的值还是原来的123456的加密值$10$cKFFTCzGOvaIHHJY2K45Zuwt8TD6oPzYi4s5MzYIBAWCLL6ZhouP2

**Comment by wenjianzhang** [comment]
谢谢您的支持，该问题已经修复！
