### ISSUE TITLE
能否讲解一下JWT与Casbin在本项目的使用？

### ISSUE THREAD

**Issue by ahua772** [wenjianzhang/go-admin#14]
首先非常感谢作者的开源，该项目是一个非常好的项目，但是在jwt与casbin部分并不是很懂，不知是否可以讲解本项目在这块是怎么使用的，大致思路即可

**Comment by wenjianzhang** [comment]
jwt只是验证用户是否有权访问，casbin是验证有权限的角色能够访问哪些资源

**Comment by W-Jie** [comment]
> 另外就是使用顺序，JWT 在前，Casbin在后，这个知道为什么吗？如果想知道请留言吧。

想知道，望解答，谢谢
