### ISSUE TITLE
swagger如何测试

### ISSUE THREAD

**Issue by chengang2** [wenjianzhang/go-admin#142]
swagger测试接口时候 
Authorization 的值怎么填。
后台方法会出现以下提示：请求方法：POST  缺少identity

**Comment by chengang2** [comment]
// @param Authorization header string true "Bearer Token"
设置了这个，但是不知道填什么值。试过用ui登入获取admin用户当前的token。但是还是不行

**Comment by wenjianzhang** [comment]
您好谢谢您的支持，对于这个问题我们会赶制一个视频出来讲解swagger的使用的，请持续关注！

**Comment by chengang2** [comment]
@wenjianzhang  能否在这里给个回答，比较急的需要这个测试

**Comment by wenjianzhang** [comment]
添加这个 // @Security

**Comment by chengang2** [comment]
@wenjianzhang 你好，我用postman测试也不行。header设置如下：
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhc2NvcGUiOiIxIiwiZXhwIjoxNTkzNzA0Njg0LCJpZGVudGl0eSI6MSwibmljZSI6ImFkbWluIiwib3JpZ19pYXQiOjE1OTM3MDEwODQsInJvbGVpZCI6MSwicm9sZWtleSI6ImFkbWluIiwicm9sZW5hbWUiOiLns7vnu5_nrqHnkIblkZgifQ.VGtBkzmMI1LrpHWfMM04_VLeWSWp8woHvenzixVVXHc

其中Authorization 值是通过ui获取的。但是依然提示错误：POST 缺少identity。
请问这个要如何获取

**Comment by chengang2** [comment]
已解决，需放在认证的方法里。谢谢
