### ISSUE TITLE
setting.yml中修改了host 值 ,  但启动时显示的链接中，仍为 127.0.0.1 

### ISSUE THREAD

**Issue by swordlet** [wenjianzhang/go-admin#143]
settings.yml中修改了host 值 ,  但启动时显示的链接中，仍为 127.0.0.1

**Comment by wenjianzhang** [comment]
您好谢谢您的建议，关于启动时log打印的127.0.0.1是方便本地调试是方便copy默认写死的，这个地方也可以进行修改，不过后续也会将此位置更新成为自动获取配置文件，请您持续关注go-admin，谢谢您对go-admin的支持和信赖。
