### ISSUE TITLE
数据权限的问题

### ISSUE THREAD

**Issue by huoli4844** [wenjianzhang/go-admin#145]
数据权限不应该加在角色上，而是应该加在用户上。
比如系统有5个公司、每个公司公司的岗位都一样； 那么我要去设置A公司的管理员只能看A公司的数据，B公司的管理员去看B公司的数据，直接在这个用户管理上，设置这个A公司管理员角色为【公司管理员】，然后数据权限只设置给他看A公司的数据就好了。
按现在的模式，那么我需要去角色里面去分别A公司的角色，B公司的角色，不够合理。

**Comment by wenjianzhang** [comment]
谢谢您的支持，go-admin的权限不是设置在角色上的而是跟个人或部门相关的哦！是否没有看清楚呢？

**Comment by huoli4844** [comment]
我的意思是，数据权限你现在是在【角色】里面去设置的。
<img width="1377" alt="图片" src="https://user-images.githubusercontent.com/29205530/86461928-568e5c80-bd5d-11ea-8a0e-78aee8a1b98f.png">

**Comment by wenjianzhang** [comment]
您好，目前系统不支持多租户，以后会考虑多租户版本，谢谢您的持续关注以及建议！
