### ISSUE TITLE
文档图片打不开了

### ISSUE THREAD

**Issue by lorenwe** [wenjianzhang/go-admin#147]
http://doc.zhangwj.com/go-admin-site/guide/intro/tutorial02.html#%E9%85%8D%E7%BD%AE%E8%A7%92%E8%89%B2%E6%9D%83%E9%99%90

**Comment by wenjianzhang** [comment]
您好，图片是放在gitee上的可以打开的哦，另外也可以通过b站来了解我们！https://www.bilibili.com/video/av455391649
