### ISSUE TITLE
用户管理--用户名称搜索和岗位管理--岗位编码搜索bug 

### ISSUE THREAD

**Issue by wivd** [wenjianzhang/go-admin#153]
用户管理中，按照用户名称搜索，后端返回全部数据

用户名称搜索时候，数据中的字段是username， 而后端取的是userName，
和https://github.com/wenjianzhang/go-admin/issues/149 描述的一致
ps：go-admin 和go-admin-uid都是最新的。
查看https://github.com/wenjianzhang/go-admin/blob/master/apis/system/sysuser.go 中的代码，
data.Username = c.Request.FormValue("userName")

和岗位管理中，按照岗位编码搜索，后端返回全部数据
https://github.com/wenjianzhang/go-admin/blob/master/apis/system/post.go
中有两条 data.PostName = c.Request.FormValue("postName")，
其中一条应该为 data.PostCode = c.Request.FormValue("postCode")
而 apis/system/post.go 中使用的函数是data.GetPage ，而data.GetPage中没有使用postCode做搜索条件。

**Comment by wenjianzhang** [comment]
谢谢您的支持，此问题已经修复！
