### ISSUE TITLE
登录失败   login fail

### ISSUE THREAD

**Issue by Zachary-Zhao** [wenjianzhang/go-admin#170]
2020/07/23 03:29:38 http: panic serving 127.0.0.1:64625: runtime error: invalid memory address or nil pointer dereference
goroutine 51 [running]:
net/http.(*conn).serve.func1(0xc00026af00)
        D:/.g/go/src/net/http/server.go:1772 +0x140
panic(0xcdc0e0, 0x28c0990)
        D:/.g/go/src/runtime/panic.go:975 +0x3f1
go-admin/middleware.CustomError.func1(0xc00012c420)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/middleware/customerror.go:44 +0x5c3
panic(0xcdc0e0, 0x28c0990)
        D:/.g/go/src/runtime/panic.go:969 +0x174
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc0009b4240)
        D:/GoProject/pkg/mod/github.com/jinzhu/gorm@v1.9.10/main.go:821 +0x2d
github.com/jinzhu/gorm.(*DB).Table(0x0, 0xdcc21d, 0x8, 0xc0000a6d00)
        D:/GoProject/pkg/mod/github.com/jinzhu/gorm@v1.9.10/main.go:515 +0x36
go-admin/models.(*Login).GetUser(0xc00028d480, 0xc000407a00, 0x14, 0xc00036dda0, 0x5, 0xc000407901, 0x1, 0xc0004079e0, 0x13, 0x14a52, ...)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/models/login.go:17 +0x81
go-admin/handler.Authenticator(0xc00012c420, 0x0, 0x20, 0x2030000, 0x2030000)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/handler/auth.go:88 +0x6cf
go-admin/pkg/jwtauth.(*GinJWTMiddleware).LoginHandler(0xc000084300, 0xc00012c420)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/pkg/jwtauth/jwtauth.go:444 +0x5f
github.com/gin-gonic/gin.(*Context).Next(0xc00012c420)
        D:/GoProject/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x42
go-admin/middleware.RequestId.func1(0xc00012c420)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/middleware/requestid.go:24 +0x1e0
github.com/gin-gonic/gin.(*Context).Next(0xc00012c420)
        D:/GoProject/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x42
go-admin/middleware.Options(0xc00012c420)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/middleware/header.go:23 +0x44
github.com/gin-gonic/gin.(*Context).Next(0xc00012c420)
        D:/GoProject/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x42
go-admin/middleware.NoCache(0xc00012c420)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/middleware/header.go:15 +0x16e
github.com/gin-gonic/gin.(*Context).Next(0xc00012c420)
        D:/GoProject/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x42
go-admin/middleware.CustomError(0xc00012c420)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/middleware/customerror.go:48 +0x55
github.com/gin-gonic/gin.(*Context).Next(0xc00012c420)
        D:/GoProject/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x42
go-admin/middleware.LoggerToFile.func1(0xc00012c420)
        D:/GoProjectMod/wenjianzhang/go-admin@v0.0.0-20200717110201-62a05daa5a7d/middleware/logger.go:21 +0x6f
github.com/gin-gonic/gin.(*Context).Next(0xc00012c420)
        D:/GoProject/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x42
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00022e000, 0xc00012c420)
        D:/GoProject/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 +0x5b7
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00022e000, 0xf500a0, 0xc000612380, 0xc0002c2200)
        D:/GoProject/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 +0x13a
net/http.serverHandler.ServeHTTP(0xc0002a8000, 0xf500a0, 0xc000612380, 0xc0002c2200)
        D:/.g/go/src/net/http/server.go:2807 +0xaa
net/http.(*conn).serve(0xc00026af00, 0xf53360, 0xc00028d180)
        D:/.g/go/src/net/http/server.go:1895 +0x873
created by net/http.(*Server).Serve
        D:/.g/go/src/net/http/server.go:2933 +0x363

**Comment by wenjianzhang** [comment]
谢谢支持，可以参考一下 https://www.bilibili.com/video/av455391649 b站中的启动视频
