### ISSUE TITLE
【建议】源文件名称统一命名方式

### ISSUE THREAD

**Issue by cppfuns** [wenjianzhang/go-admin#171]
看目前 server 源代码命名方式有 3种了，
![image](https://user-images.githubusercontent.com/7980920/88250215-7ae4b580-ccd9-11ea-87ca-2941c13f2226.png)
![image](https://user-images.githubusercontent.com/7980920/88250216-7ae4b580-ccd9-11ea-80da-ba79bf480547.png)

感谢开源

**Comment by wenjianzhang** [comment]
谢谢您的建议！同时也感谢您的关注和支持；后续会做名称的调整
