### ISSUE TITLE
【BUG】点击“生成到项目”报 “Request failed with status code 404”

### ISSUE THREAD

**Issue by cppfuns** [wenjianzhang/go-admin#172]
#### 操作步骤
系统工具->代码生成->生成到项目
#### Web  请求地址
http://127.0.0.1:8000/api/v1/gen/toproject/1
#### Server 输出log
```
INFO[7685]C:/github/go/go-admin-server/middleware/logger.go:42 go-admin/middleware.LoggerToFile.func1
 )  2020-07-23 12:08:06.5911 404            0s       127.0.0.1 GET /api/v1/gen/toproject/1
```
#### 代码版本
web 和 server 都为最新的 master 分支代码

#### 系统平台
Windows 10
go 1.14.4

**Comment by cppfuns** [comment]
前后端 master 分支代码 不匹配， 建议功能一致，目前也没release 分支，要是用户把 master 做了生产分支的话，这样不一致，会出问题

**Comment by wenjianzhang** [comment]
谢谢您的关注，前端该功能是错误操作被push到master上了，该功能即将上线，当前还在beta版本，等正式版推出我们将设置release出来，对您的困扰我们深表歉意！

**Comment by cppfuns** [comment]
> 谢谢您的关注，前端该功能是错误操作被push到master上了，该功能即将上线，当前还在beta版本，等正式版推出我们将设置release出来，对您的困扰我们深表歉意！

您太客气了~  支持开源，加油

**Comment by wenjianzhang** [comment]
您好，目前该功能已经上线版本是v1.1.0，您可以使用一下，谢谢对go-admin的支持！

**Comment by cppfuns** [comment]
> 您好，目前该功能已经上线版本是v1.1.0，您可以使用一下，谢谢对go-admin的支持！

嗯额，我测试下，有问题再回复您，加油

**Comment by cppfuns** [comment]
老哥，我试了下，
![image](https://user-images.githubusercontent.com/7980920/88869811-6313b100-d246-11ea-97c8-e9ddb9acd9e7.png)
点击完“代码生成”和配置生成后
![image](https://user-images.githubusercontent.com/7980920/88869830-6f980980-d246-11ea-8761-74c627edc164.png)

web和server 代码都生成好对应的源文件，数据库 memu 也插入数据了
但是看菜单并没有显示
![image](https://user-images.githubusercontent.com/7980920/88869938-ad952d80-d246-11ea-837b-92f2172f0e72.png)
点击菜单管理，看到菜单创建了
![image](https://user-images.githubusercontent.com/7980920/88869987-c4d41b00-d246-11ea-8443-7082e3a4b498.png)
我本想移动下，但是报
![image](https://user-images.githubusercontent.com/7980920/88870063-f9e06d80-d246-11ea-9879-76048cba0a33.png)
