### ISSUE TITLE
错误处理

### ISSUE THREAD

**Issue by hatch1994** [wenjianzhang/go-admin#174]
呃呃呃呃呃呃呃呃。。。。错误处理太没逻辑性了，难扩展。 自定义错误 “#”字符分割？ 还有日志管理，不支持层级管理，大量IO操作，性能低。完全可以采用第三方库[https://github.com/uber-go/zap](url)

**Comment by wenjianzhang** [comment]
谢谢您的建议，后续版本会对日志进行组件的升级，另外自定义错误，使用统一方法来处理的，用户端只用传入error 和message 系统自行进行处理；谢谢您的关注您的建议我们会尽快处理！

**Comment by hatch1994** [comment]
是的，我注意到了

`func HasError(err error, msg string, code ...int) {

	if err != nil {
		statusCode := 200
		if len(code) > 0 {
			statusCode = code[0]
		}
		if msg == "" {
			msg = err.Error()
		}

		log.Println(err)
		panic(fmt.Sprintf("CustomError#%v#%s", statusCode, msg))

	}
}` 
中间件customerror.go 进行recover

**Comment by wenjianzhang** [comment]
谢谢您的关注，log目前我们是要先有，也在快速的迭代，log的性能我们会考虑进去，非常感谢您的一个支持！
