### ISSUE TITLE
操作日志如何开启？

### ISSUE THREAD

**Issue by zhenghaohong** [wenjianzhang/go-admin#195]
找不到开启操作日志的地方，操作日志数据表也无记录

**Comment by ahKevinXy** [comment]
我这边也是日志看到的用户名称都不显示,这个操作日志感觉有bug

**Comment by wenjianzhang** [comment]
> 我这边也是日志看到的用户名称都不显示,这个操作日志感觉有bug

经过auth中间件的可以获得用户信息，不经中间件是不会解析用户信息

**Comment by wenjianzhang** [comment]
> 找不到开启操作日志的地方，操作日志数据表也无记录

配置文件 logger.enableddb: true 即可

**Comment by zhenghaohong** [comment]
> > 找不到开启操作日志的地方，操作日志数据表也无记录
> 
> 配置文件 logger.enableddb: true 即可

好的  非常感谢
