### ISSUE TITLE
挺不想吐槽的，真是逼的没法，可以本地先跑一下通过了，再提交到github吗，找了半天bug[吐血],第一步 ./go-admin init 都没通过

### ISSUE THREAD

**Issue by artecfeng** [wenjianzhang/go-admin#197]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wenjianzhang** [comment]
sorry，给您带来的麻烦我们深表歉意！后续会增加测试用例，谢谢您的支持！
