### ISSUE TITLE
是否有工具可以批量导入菜单,并设置admin 权限的工具,批量导入接口

### ISSUE THREAD

**Issue by ahKevinXy** [wenjianzhang/go-admin#201]
昨天写了十几个接口
然后 菜单和接口都是手动录入的
感觉这个太浪费时间了,
有没有什么方法可以快速实现这个功能

**Comment by wenjianzhang** [comment]
感谢您的支持和建议，接口可以直接从数据库生成的哦！

**Comment by ahKevinXy** [comment]
> 感谢您的支持和建议，接口可以直接从数据库生成的哦！

接口怎么生成 ,还有菜单,有文档吗

**Comment by wenjianzhang** [comment]
https://www.bilibili.com/video/BV1N54y1i71P/

**Comment by ahKevinXy** [comment]
> https://www.bilibili.com/video/BV1N54y1i71P/

哇塞好强大啊,可以,非常感谢
