### ISSUE TITLE
server.go line:59 float64保留两位小数 已修复

### ISSUE THREAD

**Issue by hatch1994** [wenjianzhang/go-admin#204]
嗨，GO-Admin-UI 前端服务监控页，我的浏览器控制台发生了一个BUG
Invalid prop: type check failed for prop "percentage". Expected Number with value 25.08, got String with value "25.08".
组件Prop 类型检查错误，预期得到的应该是一个Number 类型，go-admin /api/v1/setting/serverInfo 接口，传递的确实字符串类型。
我注意到server.go，你做了float64 保留两位小数的处理：
```go
cpuDic["Percent"] = fmt.Sprintf("%.2f",percent[0])
```
直接字符串截取“.”后面两位，然后返回字符串
-------------------------修复------------------------
```go
cpuDic["Percent"] = strconv.ParseFloat(fmt.Sprintf("%.2f", percent[0]), 2)
```
------------------------------我的修复----------------------------------
tools/float64.go
```go
func Round(f float64, n int) float64 {
	pow10_n := math.Pow10(n)
	return math.Trunc((f+0.5/pow10_n)*pow10_n) / pow10_n // TODO +0.5 是为了四舍五入，如果不希望这样去掉这个
}
```
server.go
```go
cpuDic["Percent"] = tools.Round(percent[0],2)
```

**Comment by wenjianzhang** [comment]
谢谢您的建议，但我们更希望您以pr的形式进行代码合并，谢谢您的关注和支持！
