### ISSUE TITLE
如果给一个部门添加权限

### ISSUE THREAD

**Issue by janiu-001** [wenjianzhang/go-admin#210]
您好：

看了下你的项目，向你请教一个问题！

角色可以定义对菜单接口的访问权限，在添加用户的时候可以给用户定义角色！
能不能给一个用户组，譬如一个部门添加角色呢？

**Comment by wenjianzhang** [comment]
您好感谢您的建议，目前是不支持此项配置的。后续我们会认真考虑您的建议，谢谢！
