### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by liliexuan** [wenjianzhang/go-admin#224]
win10 master 分支，sqlite 初始化失败！是否gorm有问题。 mysql正常。
go_admin.exe -- init -c=config/settings.dev.yml

warning config not found settings.ssl in the configuration
2020-08-31 00:16:03.001 [INFO] Logger init success!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xc4089d]

goroutine 1 [running]:
github.com/jinzhu/gorm.(*DB).SingularTable(0x0, 0x1)
	D:/GOPATH/pkg/mod/github.com/jinzhu/gorm@v1.9.10/main.go:194 +0x2d
go-admin/models/gorm.AutoMigrate(0x0, 0x0, 0x0)
	D:/GolandProjects/go-admin/models/gorm/gorm.go:10 +0x5a
go-admin/cmd/migrate.migrateModel(0x0, 0x0)
	D:/GolandProjects/go-admin/cmd/migrate/server.go:57 +0x16c
go-admin/cmd/migrate.run()
	D:/GolandProjects/go-admin/cmd/migrate/server.go:43 +0x133
go-admin/cmd/migrate.glob..func1(0x2eb82e0, 0xc00022e5d0, 0x0, 0x1)
	D:/GolandProjects/go-admin/cmd/migrate/server.go:23 +0x27
github.com/spf13/cobra.(*Command).execute(0x2eb82e0, 0xc00022e5c0, 0x1, 0x1, 0x0, 0x0)
	D:/GOPATH/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0xe18
github.com/spf13/cobra.(*Command).ExecuteC(0x2eb7b00, 0x2eb82e0, 0x0, 0x0)
	D:/GOPATH/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x715
github.com/spf13/cobra.(*Command).Execute(0x2eb7b00, 0x0, 0x0)
	D:/GOPATH/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887 +0x42
go-admin/cmd.Execute()
	D:/GolandProjects/go-admin/cmd/cobra.go:50 +0x34
main.main()
	D:/GolandProjects/go-admin/main.go:72 +0x27

**Comment by wenjianzhang** [comment]
谢谢您的支持，请使用最新版本尝试看看，我们并没有复显这个问题！
