### ISSUE TITLE
可否升级GORM2.0？

### ISSUE THREAD

**Issue by a5635268** [wenjianzhang/go-admin#232]
如题

**Comment by fendou** [comment]
是没有维护了?还是在憋大招吗?

**Comment by wenjianzhang** [comment]
1.2.0-beta已经升级，请下载体验，这个版本确实时间有点长了，但是也是为了更好的发展调整了一些东西。谢谢您的支持！

**Comment by fendou** [comment]
> 1.2.0-beta已经升级，请下载体验，这个版本确实时间有点长了，但是也是为了更好的发展调整了一些东西。谢谢您的支持！

厉害了哈
