### ISSUE TITLE
代码生成和字典

### ISSUE THREAD

**Issue by xiaoweihong** [wenjianzhang/go-admin#42]
你好，请问，系统里的代码生成怎么使用呀。是先在数据库里建表，然后在页面上导入，选择model.go和api.go里的内容，导入到项目里。还是有其它方式使用呢

系统里的字典功能有什么作用呢？

**Comment by wenjianzhang** [comment]
1. 创建数据库表
2. 导入
3. 预览

系统里的字典功能：常用的枚举值的动态管理
