### ISSUE TITLE
直接运行编译文件报错

### ISSUE THREAD

**Issue by axlxin** [wenjianzhang/go-admin#48]
Config File "settings" Not Found in "[/usr/local/go/path/golang.com/config]"
panic: config not found settings.database
这个要怎么解决，已经修改过setting文件

**Comment by chengxiao** [comment]
对比下master里的settings.yml文件，应该是你改setting文件的时候，改错了

**Comment by chengxiao** [comment]
> Config File "settings" Not Found in "[/usr/local/go/path/golang.com/config]"
> panic: config not found settings.database
> 这个要怎么解决，已经修改过setting文件

对比下master里的settings.yml文件，应该是你改setting文件的时候，改错了
