### ISSUE TITLE
建议添加对postgresql数据库的支持

### ISSUE THREAD

**Issue by myvker** [wenjianzhang/go-admin#53]
postgresql数据库在各个方面都是个比较优秀的选择，建议添加对postgresql的支持。

**Comment by wenjianzhang** [comment]
There is no such plan for the time being, but I also hope to receive your PR

**Comment by 107295472** [comment]
建议加个mssql

**Comment by goodforever** [comment]
I hope go-admin support postgresql too .

**Comment by wenjianzhang** [comment]
> I hope go-admin support postgresql too .

谢谢您的支持，我们会尽快支持pgsql的！

**Comment by wenjianzhang** [comment]
楼上的各位pgsql已经支持，欢迎体验！ dev 分支

**Comment by wenjianzhang** [comment]
感谢各位的支持，数据库类型已经支持了哦
