### ISSUE TITLE
AuthInit 代码中的 jwt 的 Key 设置错误

### ISSUE THREAD

**Issue by shengdoushi** [wenjianzhang/go-admin#74]
https://github.com/wenjianzhang/go-admin/blob/5da8487ea170912f7506931c3700aaa576c9824e/middleware/auth.go#L16

 config.ApplicationConfig.JwtSecret, 应该赋值给 Key 字段吧

**Comment by DewittPerry** [comment]
+1

**Comment by wenjianzhang** [comment]
已修复
