### ISSUE TITLE
角色管理 创建新的角色 分配菜单权限如何分

### ISSUE THREAD

**Issue by limuzhi** [wenjianzhang/go-admin#75]
接口权限勾选部分 如必开接口所有、日志管理所有

**Comment by wenjianzhang** [comment]
http://doc.zhangwj.com/go-admin-site/guide/intro/tutorial02.html#%E9%85%8D%E7%BD%AE%E7%B3%BB%E7%BB%9F%E8%8F%9C%E5%8D%95 可参照文档进行配置
