### ISSUE TITLE
分页查询count数包含了已删除数据

### ISSUE THREAD

**Issue by DewittPerry** [wenjianzhang/go-admin#79]
count的sql语句中没有 `表`.`deleted_at` IS NULL

**Comment by DewittPerry** [comment]
db.Where("name = ?", "jinzhu").Or("name = ?", "jinzhu 2").Find(&users).Count(&count)
//// SELECT * from USERS WHERE name = 'jinzhu' OR name = 'jinzhu 2'; (users)
//// SELECT count(*) FROM users WHERE name = 'jinzhu' OR name = 'jinzhu 2'; (count)

这种方式可以

**Comment by wenjianzhang** [comment]
已修复
