### ISSUE TITLE
gorm可以支持多种数据类型,可是代码中如果不是mysql就直接panic了

### ISSUE THREAD

**Issue by BoynChan** [wenjianzhang/go-admin#8]
./database/mysql.go包中
`if dbType != "mysql" {
		fmt.Println("db type unknow")
	}`
gorm是支持多种类型的,而且pgsql,sqlite和mysql的连接语句是一样的,可否增加其他数据库的支持呢

**Comment by wenjianzhang** [comment]
目前没有计划，以后可能会支持多种数据库类型
