### ISSUE TITLE
包引用的问题

### ISSUE THREAD

**Issue by qxs820624** [wenjianzhang/go-admin#82]
https://github.com/satori/go.uuid/blob/master/generator.go
func NewV4() (UUID, error) {
	return global.NewV4()
}

master分支：
\middleware\requestid.go
引用了"github.com/satori/go.uuid"
if requestId == "" {
			u4 := uuid.NewV4()
			requestId = u4.String()
		}

这怎么编译通过的？返回的参数个数不一致，我编译不过

2、
https://github.com/casbin/casbin/branches 
github.com/casbin/casbin 没有v2这个branch
master：
pkg\casbin\mycasbin.go 引用"github.com/casbin/casbin/v2" 我这边会报错
同理
https://github.com/casbin/gorm-adapter/branches/all 没有v2分支
gormadapter "github.com/casbin/gorm-adapter/v2" 引用报错

**Comment by wenjianzhang** [comment]
https://github.com/casbin/casbin/issues/363

**Comment by qxs820624** [comment]
u4 := uuid.NewV4()
可以编译过吗？我这边提示：
middleware\requestid.go:15:7: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values
