### ISSUE TITLE
编写go-admin应用,第2步 中的错误：apis/comtent/article.go:26:17: cannot use c.Request.FormValue("articleId") (type string) as type int in assignment apis/comtent/article.go:73:22: undefined: msg.DeletedFail

### ISSUE THREAD

**Issue by qinmin328** [wenjianzhang/go-admin#91]
c.Request.FormValue("articleId")  问题解决：data.ArticleId, _ = strconv.Atoi(c.Request.FormValue("articleId"))
undefined: msg.DeletedFail 问题解决：package msg

var (
	CreatedSuccess = "创建成功！"
	UpdatedSuccess = "更新成功！"
	DeletedSuccess = "删除成功！"
	GetSuccess     = "查询成功！"
	NotFound       = "未找到相关内容或者数据为空！"
	DeletedFail    = "删除失败！"
)

**Comment by wenjianzhang** [comment]
已添加对应配置
