### ISSUE TITLE
账号或密码错误代码（201）

### ISSUE THREAD

**Issue by oaup** [wenjianzhang/go-admin#94]
admin账户登录失败，用户数据库表中存在admin用户信息
bcrypt: hashedPassword is not the hash of the given password

2020-05-19 17:16:36.1398 [ERROR] POST /login 500 /login 127.0.0.1 账号或密码错误(代码201)
time="2020-05-19T17:16:36+08:00" level=info msg="2020-05-19 17:16:36.0379 [INFO] 200    101.9401ms       127.0.0.1 POST /login \r\n"

**Comment by xuxueyun** [comment]
你重置一下password字段 $2a$10$cKFFTCzGOvaIHHJY2K45Zuwt8TD6oPzYi4s5MzYIBAWCLL6ZhouP2
密码是 123456

**Comment by oaup** [comment]
收到，重置后可以了。

问题原因：修改个人信息后会对密码再次加密，导致密码数据变更，无法登录。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 晚上10:38
收件人:&nbsp;"wenjianzhang/go-admin"<go-admin@noreply.github.com&gt;;
抄送:&nbsp;"前进"<1151118203@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wenjianzhang/go-admin] 账号或密码错误代码（201） (#94)





 
你重置一下password字段 $2a$10$cKFFTCzGOvaIHHJY2K45Zuwt8TD6oPzYi4s5MzYIBAWCLL6ZhouP2
 密码是 123456

**Comment by chengxiao** [comment]
> 收到，重置后可以了。 问题原因：修改个人信息后会对密码再次加密，导致密码数据变更，无法登录。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Daniel"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月20日(星期三) 晚上10:38 收件人:&nbsp;"wenjianzhang/go-admin"<go-admin@noreply.github.com&gt;; 抄送:&nbsp;"前进"<1151118203@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wenjianzhang/go-admin] 账号或密码错误代码（201） (#94) 你重置一下password字段 $2a$10$cKFFTCzGOvaIHHJY2K45Zuwt8TD6oPzYi4s5MzYIBAWCLL6ZhouP2 密码是 123456 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可能是默认密码的一个前端Bug，下个版本会修复

**Comment by wenjianzhang** [comment]
已修复
